services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\FragmentKitBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../NowoFragmentKitBundle.php'

  Nowo\FragmentKitBundle\Service\FragmentFailureRenderer:
    arguments:
      $template: '%nowo_fragment_kit.fallback.template%'

  Nowo\FragmentKitBundle\Sentry\SentryFragmentFailureReporter:
    arguments:
      $config: '%nowo_fragment_kit.sentry%'

  Nowo\FragmentKitBundle\HttpKernel\Fragment\ResilientFragmentHandler:
    decorates: fragment.handler
    arguments:
      $inner: '@.inner'
